language: go
sudo: false
go:
  - 1.7
  - tip
install:
  - go get github.com/Masterminds/glide
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/glide install
  - overalls -project=github.com/mmcloughlin/pearl -- -v
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
