language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x
  - tip
install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
script:
  - go install github.com/mmcloughlin/pearl/cmd/...
  - overalls -project=github.com/mmcloughlin/pearl -ignore .git,vendor,sha1,tls -- -v
  - goveralls -coverprofile=overalls.coverprofile -service=travis-ci
